### ISSUE TITLE
Inconsistent parameter naming in Color

### ISSUE THREAD

**Issue by inxomnyaa** [pmmp/Color#40]
## Description
The methods from* in Color all use `$code` as parameter except `fromRGBA(int $c)`

## Justification
Consistency? I know there is PHPDoc which clarifies the name

This is also only the case in PM4

I am sorry for all the 🤦‍♀️ this issue creates.

**Comment by dktapps** [comment]
Fixed by 12bd55d4f59fe28a7b3354ab89d12f802dc16c23.
